/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.BacLuongModel;
import Model.ChucVuModel;
import Model.ComboItem;
import Model.NhanSuModel;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class chucvuPanel extends javax.swing.JPanel {

    /**
     * Creates new form chucvuPanel
     */
    java.awt.Frame bb;
    ArrayList<ChucVuModel> ls = new ArrayList<>();
    ArrayList<BacLuongModel> bl_ls = new ArrayList<>();
    ArrayList<NhanSuModel> dsnv = new ArrayList<>();

    String fileName = "src/SourceFile/chucvumodel.txt";
    String file_bl = "src/SourceFile/bacluongmodel.txt";
    String file_nv = "src/SourceFile/nhansumodel.txt";
    
    public chucvuPanel(java.awt.Frame mainFrame) {
        initComponents();
        bb = mainFrame;
        loadData();
    }
    
    public void loadData(){
        btn_save.setVisible(false);
        btn_cancel.setVisible(false);
        
        // Lay danh sach bac luong
        try {
            FileInputStream fi=new FileInputStream(file_bl);
            ObjectInputStream ois=new ObjectInputStream(fi);
            BacLuongModel bl;
            bl_ls = new ArrayList<>();
            while(fi.available() > 0)
            {
                bl = (BacLuongModel) ois.readObject();
                bl_ls.add(bl);
            }
            fi.close();
            ois.close();
            for(BacLuongModel s : bl_ls)
                cbo_bacluong.addItem(s.getBacLuong());
            reLoad();
        } catch (Exception ex) {
             System.out.print("lỗi đọc file bậc lương");
        }
        
        // Lay danh sach nhan vien
        try {
            FileInputStream fi=new FileInputStream(file_nv);
            ObjectInputStream ois=new ObjectInputStream(fi);
            NhanSuModel nv;
            dsnv = new ArrayList<>();
            while(fi.available() > 0)
            {
                nv = (NhanSuModel) ois.readObject();
                dsnv.add(nv);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
            System.out.println("Lỗi đọc file nhân sự");
        }
        reLoad();
    }
    
    public void reLoad(){
        try {
            FileInputStream fi=new FileInputStream(fileName);
            ObjectInputStream ois=new ObjectInputStream(fi);
            ChucVuModel cv;
            ls = new ArrayList<>();
            while(fi.available() > 0)
            {
                cv = (ChucVuModel) ois.readObject();
                ls.add(cv);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
             System.out.print("lỗi đọc file chức vụ");
        }
        cbo_chucvu.removeAllItems();
        for(ChucVuModel z: ls)
        {
            cbo_chucvu.addItem(new ComboItem(z.getTenCV(),z.getMaCV()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_phucap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbo_chucvu = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_soluong = new javax.swing.JTextField();
        lb_soluongns = new javax.swing.JLabel();
        cbo_bacluong = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Mã chức vụ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 40));
        add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Tên chức vụ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 40));
        add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 210, 40));
        add(txt_phucap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Phụ cấp");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Bậc lương");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Danh sách chức vụ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, 40));

        cbo_chucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_chucvuItemStateChanged(evt);
            }
        });
        add(cbo_chucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 210, 40));

        btn_save.setBackground(new java.awt.Color(0, 102, 102));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("LƯU");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 85, 41));

        btn_cancel.setBackground(new java.awt.Color(0, 102, 102));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("HỦY");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 85, 41));

        btn_add.setBackground(new java.awt.Color(0, 102, 102));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("THÊM");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 85, 41));

        btn_update.setBackground(new java.awt.Color(0, 102, 102));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("SỬA");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 85, 41));

        btn_delete.setBackground(new java.awt.Color(0, 102, 102));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("XÓA");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 85, 41));
        add(txt_soluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 40));

        lb_soluongns.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_soluongns.setText("Số lượng nhân sự");
        add(lb_soluongns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 40));

        add(cbo_bacluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        cbo_chucvu.setEnabled(true);
        cbo_chucvu.setSelectedIndex(-1);
        btn_save.setVisible(false);
        btn_cancel.setVisible(false);
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_add.setEnabled(true);
        txt_id.setEnabled(false);
        txt_soluong.setEnabled(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        getStartAdd();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try{
            if(txt_id.getText().equals("")){
                txt_id.requestFocus();
                throw new Exception("Mã chức vụ không được để trống!");
            }
            if(txt_name.getText().equals("")){
                txt_name.requestFocus();
                throw new Exception("Tên chức vụ không được để trống!");
            }
            if(txt_phucap.getText().equals("")){
                txt_phucap.requestFocus();
                throw new Exception("Phụ cấp không được để trống!");
            }
            if(!txt_phucap.getText().matches("[0-9\\.]+")){
                txt_phucap.requestFocus();
                throw new Exception("Phụ cấp phải là số!");
            }
            if(cbo_bacluong.getSelectedIndex()==-1){
                throw new Exception("Vui lòng chọn bậc lương!");
            }
            for(ChucVuModel cv : ls) {
                if(cv.getMaCV().equals(txt_id.getText())){
                    txt_id.requestFocus();
                    throw new Exception("Mã chức vụ này đã tồn tại!");
                }
            }
            
            String maCV = txt_id.getText();
            String tenCV = txt_name.getText();
            Double phuCap = Double.valueOf(txt_phucap.getText());
            int BacLuong = (Integer)cbo_bacluong.getSelectedItem();
            ChucVuModel newcv = new ChucVuModel(maCV, tenCV, phuCap, BacLuong);
            try {
                ls.add(newcv);
                FileOutputStream fs=new FileOutputStream(fileName);
                ObjectOutputStream os=new ObjectOutputStream(fs);
                for(ChucVuModel cv : ls)
                    os.writeObject(cv);
                fs.close();
                os.close();
                
                reLoad();
                cbo_chucvu.setEnabled(true);
                cbo_chucvu.setSelectedIndex(0);
                btn_save.setVisible(false);
                btn_cancel.setVisible(false);
                btn_update.setEnabled(true);
                btn_delete.setEnabled(true);
                btn_add.setEnabled(true);
                txt_id.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
            }
            catch(Exception ex) {
                System.out.println("Lỗi ghi file chức vụ");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Thêm thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void cbo_chucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_chucvuItemStateChanged
        if(cbo_chucvu.getSelectedItem()!=null){
            String choose = ((ComboItem)cbo_chucvu.getSelectedItem()).getValue();
            int count = 0;
            for(NhanSuModel nv : dsnv) {
                if(nv.getMaCV().equals(choose))
                    count++;
            }
            for(ChucVuModel z: ls)
                if(choose.equals(z.getMaCV())) {
                    txt_id.setText(z.getMaCV());
                    txt_name.setText(z.getTenCV());
                    txt_phucap.setText(String.valueOf(String.valueOf(new DecimalFormat("#0").format(z.getPhuCap()))));
                    if(z.getBacLuong()==0)
                        cbo_bacluong.setSelectedIndex(-1);
                    else{
                        cbo_bacluong.setSelectedItem(z.getBacLuong());
                    txt_soluong.setText(String.valueOf(count));
                    txt_soluong.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_cbo_chucvuItemStateChanged

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int choose = cbo_chucvu.getSelectedIndex();
        try{
            if(txt_name.getText().equals("")){
                txt_name.requestFocus();
                throw new Exception("Tên chức vụ không được để trống!");
            }
            if(txt_phucap.getText().equals("")){
                txt_phucap.requestFocus();
                throw new Exception("Phụ cấp không được để trống!");
            }
            if(!txt_phucap.getText().matches("[0-9\\.]+")){
                txt_phucap.requestFocus();
                throw new Exception("Phụ cấp phải là số!");
            }
            if(cbo_bacluong.getSelectedIndex()==-1){
                throw new Exception("Vui lòng chọn bậc lương!");
            }
            
            String maCV = txt_id.getText();
            String tenCV = txt_name.getText();
            Double phuCap = Double.valueOf(txt_phucap.getText());
            int BacLuong = (Integer)cbo_bacluong.getSelectedItem();
            ChucVuModel newcv = new ChucVuModel(maCV, tenCV, phuCap, BacLuong);
            
            int index = ls.indexOf(newcv);
            if(index != -1)
                ls.set(index, newcv);
            try {
                FileOutputStream fs=new FileOutputStream(fileName);
                ObjectOutputStream os=new ObjectOutputStream(fs);
                for(ChucVuModel cv : ls)
                    os.writeObject(cv);
                fs.close();
                os.close();
                
                reLoad();
                cbo_chucvu.setSelectedIndex(choose);
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            }
            catch(Exception ex) {
                System.out.println("Lỗi ghi file chức vụ");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Sửa thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if(JOptionPane.showConfirmDialog (null, "Bạn chắc chắn muốn xóa bản ghi này?","Bạn chắc chứ?",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            try{
                int choose = cbo_chucvu.getSelectedIndex();
                String maCV = txt_id.getText();
                String tenCV = txt_name.getText();
                Double phuCap = Double.valueOf(txt_phucap.getText());
                int BacLuong = (Integer)cbo_bacluong.getSelectedItem();
                ChucVuModel xoacv = new ChucVuModel(maCV, tenCV, phuCap, BacLuong);
                int index = ls.indexOf(xoacv);
                if(index != -1) {
                    ls.remove(index);
                }
                else
                    throw new Exception("Không tồn tại chức vụ này!");
                try {
                    FileOutputStream fs=new FileOutputStream(fileName);
                    ObjectOutputStream os=new ObjectOutputStream(fs);
                    for(ChucVuModel cv : ls)
                        os.writeObject(cv);
                    fs.close();
                    os.close();
                    JOptionPane.showMessageDialog(this, "Xoá thành công!");
                    reLoad();
                }
                catch(Exception ex) {
                    System.out.println("Lỗi ghi file chức vụ");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Xoá thất bại!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void getStartAdd(){
        txt_id.setEnabled(true);
        btn_save.setVisible(true);
        btn_cancel.setVisible(true);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_add.setEnabled(false);
        cbo_chucvu.setEnabled(false);
        cbo_chucvu.setSelectedIndex(-1);
        txt_id.setText("");
        txt_name.setText("");
        txt_phucap.setText("");
        cbo_bacluong.setSelectedIndex(-1);
        txt_soluong.setText("0");
        txt_soluong.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<Integer> cbo_bacluong;
    private javax.swing.JComboBox<ComboItem> cbo_chucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_soluongns;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phucap;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
