/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.CustomTable.HoSoTableModel;
import Model.NhanSuHoSoModel;
import Model.NhanSuModel;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author asus
 */
public class hosoPanel extends javax.swing.JPanel {

    /**
     * Creates new form hosoPanel
     */
    
    hosoPanel aa;
    java.awt.Frame bb;
    ArrayList<NhanSuHoSoModel> dsHoSo = new ArrayList<>();
    ArrayList<NhanSuModel> dsnv = new ArrayList<>();
    String fileName = "src/SourceFile/nhansumodel.txt";
    
    public hosoPanel(java.awt.Frame mainFrame) {
        initComponents();
        aa = this;
        bb = mainFrame;
        LoadData();
    }
    
    public void LoadData(){
        try {
            FileInputStream fi=new FileInputStream(fileName);
            ObjectInputStream ois=new ObjectInputStream(fi);
            NhanSuModel nv;
            dsnv = new ArrayList<>();
            while(fi.available() > 0)
            {
                nv = (NhanSuModel) ois.readObject();
                dsnv.add(nv);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
            System.out.println("Lỗi đọc file nhân sự");
        }
        dsHoSo.clear();
        for(int i = 0; i< dsnv.size();i++)
        {
            NhanSuHoSoModel a =  new NhanSuHoSoModel(dsnv.get(i));
            dsHoSo.add(a);
        }
        reloadTable();
    }
        
    public void reloadTable(){
        table_ns.setModel(new HoSoTableModel(dsHoSo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ns = new javax.swing.JTable();

        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        table_ns.setModel(new HoSoTableModel());
        jScrollPane1.setViewportView(table_ns);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        detailInforAdd z = new detailInforAdd(aa, bb, true);
        z.setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(table_ns.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this,"Chưa chọn dòng","Thông báo", WIDTH);
        }
        else {
            String mans = (String)table_ns.getValueAt(table_ns.getSelectedRow(), 0);
            detailHoSo z = new detailHoSo(aa, mans, bb, true);
            z.setVisible(true);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int dongChon = table_ns.getSelectedRow(); 
        if (dongChon != -1) {
            int ret=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xoá?", "Xóa nhân sự",
                JOptionPane.YES_NO_OPTION);
            
            if(ret==JOptionPane.YES_OPTION) {
                dsnv.remove(dongChon);
                try {
                    FileOutputStream fs=new FileOutputStream(fileName);
                    ObjectOutputStream os=new ObjectOutputStream(fs);
                    for(NhanSuModel nv : dsnv)
                        os.writeObject(nv);
                    fs.close();
                    os.close();

                    JOptionPane.showMessageDialog(this,"Xóa thành công!");
                    LoadData();
                } catch(Exception ex) {
                    System.out.println("Lỗi ghi file nhân sự");
                }
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Chưa chọn dòng xóa","Thông báo", WIDTH);
    }//GEN-LAST:event_btn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_ns;
    // End of variables declaration//GEN-END:variables
}
