/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.CustomTable.BangLuongTableModel;
import Model.NhanSuModel;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author asus
 */
public class luongPanel extends javax.swing.JPanel {

    /**
     * Creates new form luongPanel
     */
    java.awt.Frame bb;
    ArrayList<NhanSuModel> dsnv = new ArrayList<>();
    String file_ns = "src/SourceFile/nhansumodel.txt";
    
    public luongPanel(java.awt.Frame mainFrame) {
        initComponents();
        bb=mainFrame;
        try {
            FileInputStream fi=new FileInputStream(file_ns);
            ObjectInputStream ois=new ObjectInputStream(fi);
            NhanSuModel nv;
            dsnv = new ArrayList<>();
            while(fi.available() > 0)
            {
                nv = (NhanSuModel) ois.readObject();
                dsnv.add(nv);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
            System.out.println("Lỗi đọc file nhân sự");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_edit = new javax.swing.JButton();
        btn_calc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_luong = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_edit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_edit.setText("Chỉnh sửa thông số tính lương");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_calc.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_calc.setText("Tính lương");
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_calc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_luong.setModel(new BangLuongTableModel());
        jScrollPane1.setViewportView(table_luong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        salaryCalculatorEdit zEdit = new salaryCalculatorEdit(bb, true);
        zEdit.setVisible(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed
        try{
            LoadLuongTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi\n"+e.getMessage());
        }
    }//GEN-LAST:event_btn_calcActionPerformed

    private void LoadLuongTable(){
        table_luong.setModel(new BangLuongTableModel(dsnv));
        table_luong.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table_luong.getColumnModel().getColumn(0).setPreferredWidth(100);
        table_luong.getColumnModel().getColumn(1).setPreferredWidth(150);
        table_luong.getColumnModel().getColumn(2).setPreferredWidth(110);
        table_luong.getColumnModel().getColumn(3).setPreferredWidth(158);
        table_luong.getColumnModel().getColumn(4).setPreferredWidth(130);
        table_luong.getColumnModel().getColumn(5).setPreferredWidth(100);
        table_luong.getColumnModel().getColumn(6).setPreferredWidth(150);
        table_luong.getColumnModel().getColumn(7).setPreferredWidth(90);
        table_luong.getColumnModel().getColumn(8).setPreferredWidth(90);
        table_luong.getColumnModel().getColumn(9).setPreferredWidth(130);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calc;
    private javax.swing.JButton btn_edit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_luong;
    // End of variables declaration//GEN-END:variables
}
