/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.BacLuongModel;
import Model.ChucVuModel;
import Model.CustomTable.BacLuongTableModel;
import Model.ThongTinTinhLuong;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class salaryCalculatorEdit extends javax.swing.JDialog {

    /**
     * Creates new form salaryCalculatorEdit
     */
    
    hosoPanel previousPanel;
    String fileName = "src/SourceFile/bacluongmodel.txt";
    String fileCV = "src/SourceFile/chucvumodel.txt";
    String file_ts = "src/SourceFile/thongsotinhluong.txt";
    ArrayList<BacLuongModel> ls = new ArrayList<>();
    ArrayList<ChucVuModel> cv_ls = new ArrayList<>();
    ThongTinTinhLuong ts = new ThongTinTinhLuong(0, 0, 0, 0, 0);
    
    public salaryCalculatorEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        // Đọc danh sách chức vụ
        try {
            FileInputStream fi=new FileInputStream(fileCV);
            ObjectInputStream ois=new ObjectInputStream(fi);
            ChucVuModel cv;
            cv_ls = new ArrayList<>();
            while(fi.available() > 0)
            {
                cv = (ChucVuModel) ois.readObject();
                cv_ls.add(cv);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
             System.out.print("lỗi đọc file chức vụ");
        }
        
        // Đọc thông số tính lương
        try {
            FileInputStream fi=new FileInputStream(file_ts);
            ObjectInputStream ois=new ObjectInputStream(fi);
            ts = (ThongTinTinhLuong) ois.readObject();
            fi.close();
            ois.close();
        } catch (Exception ex) {
             System.out.println("Lỗi đọc file thông số tính lương");
        }
        loadTableData();
        table_luong.revalidate();
    }
    
    public void loadTableData(){
        try {
            FileInputStream fi=new FileInputStream(fileName);
            ObjectInputStream ois=new ObjectInputStream(fi);
            BacLuongModel bl;
            ls = new ArrayList<>();
            while(fi.available() > 0)
            {
                bl = (BacLuongModel) ois.readObject();
                ls.add(bl);
            }
            fi.close();
            ois.close();
        } catch (Exception ex) {
             System.out.print("lỗi đọc file bậc lương");
        }
        table_luong.setModel(new BacLuongTableModel(ls));
        txt_luongcb.setText(String.valueOf(ts.getLuongCB()));
        txt_namthamnien.setText(String.valueOf(ts.getNamThamNiem()));
        txt_thuongcoban.setText(String.valueOf(ts.getThuongCB()));
        txt_thuongthem.setText(String.valueOf(ts.getThuongThem()));
        txt_baohiem.setText(String.valueOf(ts.getBaoHiem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_bac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_heso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_luong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_luongcb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_namthamnien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_thuongcoban = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_thuongthem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_baohiem = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_add.setBackground(new java.awt.Color(0, 102, 102));
        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Thêm bậc lương");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(0, 102, 102));
        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Xóa bậc lương");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(0, 102, 102));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Sửa bậc lương");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Bậc lương");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Hệ số lương");

        table_luong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_luongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_luong);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Lương cơ bản");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Năm bắt đầu hưởng thâm niên");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Phần trăm thưởng thâm niên cơ bản");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Phần trăm thưởng thêm hàng năm");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Chi phí bảo hiểm");

        btn_save.setBackground(new java.awt.Color(0, 204, 0));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("LƯU");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 51, 51));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("HỦY BỎ");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_heso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_bac, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_baohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_thuongthem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_namthamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_luongcb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_thuongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_heso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_luongcb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_namthamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_thuongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_thuongthem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_baohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void table_luongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_luongMouseClicked
                            
        int row = table_luong.rowAtPoint(evt.getPoint());
        if(row>=0)
        {
            txt_bac.setText(table_luong.getValueAt(row, 0).toString());
            txt_heso.setText(table_luong.getValueAt(row, 1).toString());
        }
    }//GEN-LAST:event_table_luongMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try{
            if(txt_bac.getText().equals("")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương không được để trống!");
            }
            if(txt_heso.getText().equals("")){
                txt_heso.requestFocus();
                throw new Exception("Hệ số lương không được để trống!");
            }
            if(!txt_bac.getText().matches("[0-9]+")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương phải là số!");
            }
            if(!txt_heso.getText().matches("[0-9\\.]+")){
                txt_heso.requestFocus();
                throw new Exception("Hệ số lương phải là số!");
            }
            int bl = Integer.valueOf(txt_bac.getText());
            for(BacLuongModel luong : ls) {
                if(luong.getBacLuong() == bl){
                    txt_bac.requestFocus();
                    throw new Exception("Bậc lương này đã tồn tại!");
                }
            }
            Double hsl = Double.valueOf(txt_heso.getText());
            BacLuongModel newbl = new BacLuongModel(bl, hsl);
            try {
                ls.add(newbl);
                FileOutputStream fs=new FileOutputStream(fileName);
                ObjectOutputStream os=new ObjectOutputStream(fs);
                for(BacLuongModel luong : ls)
                    os.writeObject(luong);
                fs.close();
                os.close();
                
                loadTableData();
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
            }
            catch(Exception ex) {
                System.out.println("Lỗi ghi file");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thêm thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try{
            if(txt_bac.getText().equals("")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương không được để trống!");
            }
            if(txt_heso.getText().equals("")){
                txt_heso.requestFocus();
                throw new Exception("Hệ số lương không được để trống!");
            }
            if(!txt_bac.getText().matches("[0-9]+")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương phải là số!");
            }
            if(!txt_heso.getText().matches("[0-9\\.]+")){
                txt_heso.requestFocus();
                throw new Exception("Hệ số lương phải là số!");
            }
            int bl = Integer.valueOf(txt_bac.getText());
            Double hsl = Double.valueOf(txt_heso.getText());
            BacLuongModel newbl = new BacLuongModel(bl, hsl);
            int index = ls.indexOf(newbl);
            if(index != -1)
                ls.set(index, newbl);
            else
                throw new Exception("Bậc lương không tồn tại\nVui lòng chọn bậc lương để sửa!");
            try {
                FileOutputStream fs=new FileOutputStream(fileName);
                ObjectOutputStream os=new ObjectOutputStream(fs);
                for(BacLuongModel bac : ls)
                    os.writeObject(bac);
                fs.close();
                os.close();
                
                loadTableData();
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            }
            catch(Exception ex) {
                System.out.println("Lỗi ghi file");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Sửa thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try{
            if(txt_bac.getText().equals("")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương không được để trống!");
            }
            if(!txt_bac.getText().matches("[0-9]+")){
                txt_bac.requestFocus();
                throw new Exception("Bậc lương phải là số!");
            }
            int bl = Integer.valueOf(txt_bac.getText());
            Double hsl = Double.valueOf(txt_heso.getText());
            BacLuongModel xoabl = new BacLuongModel(bl, hsl);
            int index = ls.indexOf(xoabl);
            if(index == -1) {
                throw new Exception("Bậc lương không tồn tại\nVui lòng chọn bậc lương để xoá!");
            }
            for(ChucVuModel cv : cv_ls) {
                if(cv.getBacLuong() == bl)
                    throw new Exception("Có một số chức vụ đang sở hữu bậc lương này\nVui lòng chỉnh lại trước khi xoá!");
            }
            ls.remove(index);
            try {
                    FileOutputStream fs=new FileOutputStream(fileName);
                    ObjectOutputStream os=new ObjectOutputStream(fs);
                    for(BacLuongModel luong : ls)
                        os.writeObject(luong);
                    fs.close();
                    os.close();
                    loadTableData();
                    JOptionPane.showMessageDialog(this, "Xoá thành công!");
                }
                catch(Exception ex) {
                    JOptionPane.showMessageDialog(this, "Xoá thất bại!");
                    System.out.println("Lỗi ghi file bậc lương");
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Xoá thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try{
            if(txt_luongcb.getText().equals("")){
                txt_luongcb.requestFocus();
                throw new Exception("Lương cơ bản không được để trống!");
            }
            if(!txt_luongcb.getText().matches("[0-9]+")){
                txt_luongcb.requestFocus();
                throw new Exception("Lương cơ bản chỉ gồm số!");
            }
            if(txt_namthamnien.getText().equals("")){
                txt_namthamnien.requestFocus();
                throw new Exception("Năm bắt đầu hưởng thâm niên không được để trống!");
            }
            if(!txt_namthamnien.getText().matches("[0-9]+")){
                txt_namthamnien.requestFocus();
                throw new Exception("Năm bắt đầu hưởng thâm niên phải là số!");
            }
            if(txt_thuongcoban.getText().equals("")){
                txt_thuongcoban.requestFocus();
                throw new Exception("Phần thăm thưởng thâm niên không được để trống!");
            }
            if(!txt_thuongcoban.getText().matches("[0-9\\.]+")){
                txt_thuongcoban.requestFocus();
                throw new Exception("Phần trăm thưởng thêm niên thâm niên phải là số!");
            }
            if(txt_thuongthem.getText().equals("")){
                txt_thuongthem.requestFocus();
                throw new Exception("Phần thăm thưởng thâm niên thêm từng năm không được để trống!");
            }
            if(!txt_thuongthem.getText().matches("[0-9\\.]+")){
                txt_thuongthem.requestFocus();
                throw new Exception("Phần trăm thưởng thâm niên thêm từng năm niên thâm niên phải là số!");
            }
            if(txt_baohiem.getText().equals("")){
                txt_baohiem.requestFocus();
                throw new Exception("Chi phí bảo hiểm không được để trống!");
            }
            if(!txt_baohiem.getText().matches("[0-9]+")){
                txt_baohiem.requestFocus();
                throw new Exception("Chi phí bảo hiểm phải là số!");
            }
            int luongCB = Integer.valueOf(txt_luongcb.getText());
            int nam = Integer.valueOf(txt_namthamnien.getText());
            double thuongCB = Double.valueOf(txt_thuongcoban.getText());
            double thuongTh = Double.valueOf(txt_thuongthem.getText());
            int baohiem = Integer.valueOf(txt_baohiem.getText());
            
            ts = new ThongTinTinhLuong(thuongCB, thuongTh, luongCB, baohiem, nam);
            
            try {
                    FileOutputStream fs=new FileOutputStream(file_ts);
                    ObjectOutputStream os=new ObjectOutputStream(fs);
                    os.writeObject(ts);
                    fs.close();
                    os.close();
                    JOptionPane.showMessageDialog(this, "Lưu thành công!");
                    loadTableData();
                }
                catch(Exception ex) {
                    System.out.println("Lỗi ghi file thông số tính lương");
                }
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lưu thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salaryCalculatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salaryCalculatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salaryCalculatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salaryCalculatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                salaryCalculatorEdit dialog = new salaryCalculatorEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_luong;
    private javax.swing.JTextField txt_bac;
    private javax.swing.JTextField txt_baohiem;
    private javax.swing.JTextField txt_heso;
    private javax.swing.JTextField txt_luongcb;
    private javax.swing.JTextField txt_namthamnien;
    private javax.swing.JTextField txt_thuongcoban;
    private javax.swing.JTextField txt_thuongthem;
    // End of variables declaration//GEN-END:variables
}
